### ISSUE TITLE
New functionalities 

### ISSUE THREAD

**Issue by JurajLenco** [Nesvilab/PD-Nodes#17]
Hi,
I like to use MSFragger via the PD node. For me, It is currently the most straightforward way to visualize the MSFragger results. Do you plan to implement also the new functionalities that are available in the current version of FragPipe to the nodes, such as PTM-Shaperd, deisotoping, mass calibration, and parameter optimization?
Thanks,
J. Lenco

**Comment by anesvi** [comment]
Dear J. Lenco,

deisotoping, mass calibration, and parameter optimization – these are part of MSFragger. I think they are already available in the current PD node. If not, they will be when  we update the node.

However, other tools such as PTM-Shepherd, we do not see a simple way to add them to PD. We will keep your suggestion in mind, but need to see what it involves.

Best
Alexey

**Comment by JurajLenco** [comment]
Thank you for the fast reply and great news,
Juraj
